### ISSUE TITLE
Base Type stairs, crashes the game

### ISSUE THREAD

**Issue by LucasLDZ** [U1timateJ7/CustomBlocks#14]
Making a block with "base": "stairs" crashes the game when it tries to load resources.

Changing it to slab works fine. Not sure if other bases are broke, but this was something that was working in 1.18.2 version of the mod, that broke in the 1.19 version. Not sure the log is helpful at all, because it doesn't mention stairs where it starts to crash.

Unhandled game exception
java.lang.IllegalStateException: Some intrusive holders were not added to registry: [Reference{null=Block{minecraft:air}}]
    at net.minecraft.class_2370.method_40276(class_2370.java:352)
    at net.minecraft.class_2378.method_40292(class_2378.java:404)
    at net.minecraft.class_310.handler$zjh001$onStart(class_310.java:6403)
    at net.minecraft.class_310.method_1514(class_310.java:713)
    at net.minecraft.client.main.Main.main(Main.java:237)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
13:17:55.402
Stopping!
13:17:55.542
emissive suffixes loaded: [_e]
13:17:55.544
Shutdown failure!
java.util.ConcurrentModificationException
    at java.base/java.util.HashMap.forEach(HashMap.java:1424)
    at net.minecraft.class_1060.close(class_1060.java:173)
    at net.minecraft.class_310.close(class_310.java:1058)
    at net.minecraft.class_310.method_1490(class_310.java:1034)
    at net.minecraft.client.main.Main.main(Main.java:253)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by U1timateJ7** [comment]
Any crash report is helpful. Thanks for telling me.
